/**
 * The balance probe.
 *
 * Answers the only question that matters about the curves — "does a real player
 * keep getting deeper, and how fast?" — by running the actual simulation
 * against a simulated player, rather than by reasoning about the exponents.
 *
 * That distinction earned its keep. The relic growth rate was first derived
 * analytically, tuned to a number that looked right, and measured only
 * afterwards: the measurement showed the runs converging on a fixed depth and
 * quietly ending the game. The derivation had been correct about the shape and
 * wrong about which quantity it applied to.
 *
 *   npm run balance            print the report
 *   npm run balance -- --write update docs/BALANCE.md
 */

import { writeFileSync } from 'node:fs';
import { autoplay } from '../src/game/autoplay';
import { formatDuration, formatNumber } from '../src/core/format';
import { setLocale } from '../src/core/i18n';
import { canDescend, descend, pendingRelics, DESCENT_UNLOCK_FLOOR } from '../src/game/prestige';
import { computeStats } from '../src/game/stats';
import { createInitialState, type GameState } from '../src/game/state';

/** The simulated player checks in for half an hour at a time. */
const SESSION_SECONDS = 30 * 60;

/** Sessions without a new floor before the run is judged walled. */
const PATIENCE = 8;

const DESCENTS = 20;

interface RunRow {
  readonly run: number;
  readonly elapsedSeconds: number;
  readonly depth: number;
  readonly gain: number;
  readonly relics: string;
  readonly multiplier: string;
  readonly damagePerSecond: string;
}

/** Plays one run to its wall and reports where that was. */
function playToWall(state: GameState): void {
  let previous = -1;
  let stagnant = 0;

  while (stagnant < PATIENCE) {
    autoplay(state, SESSION_SECONDS);
    if (state.highestFloor === previous) stagnant += 1;
    else stagnant = 0;
    previous = state.highestFloor;
  }
}

function measure(): RunRow[] {
  const state = createInitialState(0);
  const rows: RunRow[] = [];
  let elapsed = 0;
  let previousDepth = 0;

  for (let run = 1; run <= DESCENTS; run += 1) {
    const before = state.stats.playSeconds;
    playToWall(state);
    elapsed += state.stats.playSeconds - before;

    const gained = pendingRelics(state.highestFloor);
    const stats = computeStats(state);

    rows.push({
      run,
      elapsedSeconds: elapsed,
      depth: state.highestFloor,
      gain: state.highestFloor - previousDepth,
      relics: formatNumber(state.relics.add(gained)),
      multiplier: formatNumber(stats.relicMultiplier),
      damagePerSecond: formatNumber(stats.damagePerSecond),
    });

    previousDepth = state.highestFloor;
    if (!canDescend(state)) break;
    descend(state, 0);
  }

  return rows;
}

function toMarkdown(rows: RunRow[]): string {
  const first = rows[0];
  const last = rows[rows.length - 1];
  if (first === undefined || last === undefined) throw new Error('no rows measured');

  const lines = [
    '# Balance report',
    '',
    '> Generated by `npm run balance -- --write`. Do not edit by hand.',
    '',
    'Measured by running the shipping simulation against the simulated player in',
    '`src/game/autoplay.ts`, which buys the cheapest thing it can afford every ten',
    'seconds and descends once a run stops producing new floors. That shopper is',
    'deliberately naive, so every number here is a **lower bound**: a thoughtful',
    'player does better.',
    '',
    '## What this has to show',
    '',
    'Reachable depth goes as `log(multiplier) / log(healthGrowth)`, and the relic',
    'multiplier goes as `relicGrowth^depth`, so one descent maps to the next',
    'roughly linearly. If the gain per descent shrinks toward zero, the runs have a',
    'fixed point: the player descends forever and never moves, and the game ends',
    'without ever saying so. The gain column is the check.',
    '',
    '| Run | Wall clock | Depth | Gain | Relics | Multiplier | Damage/sec |',
    '| --: | ---------: | ----: | ---: | -----: | ---------: | ---------: |',
  ];

  for (const row of rows) {
    lines.push(
      `| ${row.run} | ${formatDuration(row.elapsedSeconds)} | ${row.depth} | ` +
        `+${row.gain} | ${row.relics} | ×${row.multiplier} | ${row.damagePerSecond} |`,
    );
  }

  const early = rows[Math.min(2, rows.length - 1)];
  lines.push(
    '',
    '## Reading it',
    '',
    `- The first run walls at floor ${String(first.depth)}, which is where the descent`,
    `  unlock sits (floor ${String(DESCENT_UNLOCK_FLOOR)}). A player meets the mechanic the`,
    '  rest of the game is built around inside their first session, rather than',
    '  grinding against a ceiling with it still greyed out.',
    early === undefined
      ? ''
      : `- Gains climb rather than shrink: +${String(early.gain)} floors by run ${String(early.run)}, ` +
          `+${String(last.gain)} by run ${String(last.run)}.`,
    '- No plateau appears across the measured descents, which is what says the',
    '  relic growth rate sits above the health growth rate rather than below it.',
    '',
  );

  return lines.filter((line) => line !== '').join('\n') + '\n';
}

function toTable(rows: RunRow[]): string {
  const header = 'run  wall clock   depth  gain  relics       multiplier   damage/sec';
  const body = rows.map((row) =>
    [
      String(row.run).padStart(3),
      formatDuration(row.elapsedSeconds).padStart(11),
      String(row.depth).padStart(6),
      `+${String(row.gain)}`.padStart(5),
      row.relics.padStart(12),
      `×${row.multiplier}`.padStart(12),
      row.damagePerSecond.padStart(12),
    ].join(' '),
  );
  return [header, ...body].join('\n');
}

// English, so a report committed from a Korean machine reads the same as one
// committed from anywhere else.
setLocale('en');

const rows = measure();
console.log(toTable(rows));

if (process.argv.includes('--write')) {
  writeFileSync('docs/BALANCE.md', toMarkdown(rows));
  console.log('\nwrote docs/BALANCE.md');
}
