/**
 * The balance probe.
 *
 * Answers the only question that matters about the curves — "does a real player
 * keep getting further, and how fast?" — by running the actual simulation
 * against a simulated player, rather than by reasoning about the exponents.
 *
 * That distinction earned its keep. The relic growth rate was first derived
 * analytically, tuned to a number that looked right, and measured only
 * afterwards: the measurement showed the stones converging on a fixed stage and
 * quietly ending the game. The derivation had been correct about the shape and
 * wrong about which quantity it applied to.
 *
 *   npm run balance            print the report
 *   npm run balance -- --write update docs/BALANCE.md
 */

import { writeFileSync } from 'node:fs';
import { autoplay } from '../src/game/autoplay';
import { formatDuration, formatNumber } from '../src/core/format';
import { setLocale } from '../src/core/i18n';
import {
  canCompress,
  compress,
  pendingCrystals,
  COMPRESSION_UNLOCK_STAGE,
} from '../src/game/prestige';
import { computeStats } from '../src/game/stats';
import { createInitialState, type GameState } from '../src/game/state';

/** The simulated player checks in for half an hour at a time. */
const SESSION_SECONDS = 30 * 60;

/** Sessions without a new floor before the run is judged walled. */
const PATIENCE = 8;

const DESCENTS = 20;

interface StoneRow {
  readonly run: number;
  readonly elapsedSeconds: number;
  readonly stage: number;
  readonly gain: number;
  readonly crystals: string;
  readonly multiplier: string;
  readonly absorption: string;
}

/** Grows one stone to its wall and reports where that was. */
function growToWall(state: GameState): void {
  let previous = -1;
  let stagnant = 0;

  while (stagnant < PATIENCE) {
    autoplay(state, SESSION_SECONDS);
    if (state.highestStage === previous) stagnant += 1;
    else stagnant = 0;
    previous = state.highestStage;
  }
}

function measure(): StoneRow[] {
  const state = createInitialState(0);
  const rows: StoneRow[] = [];
  let elapsed = 0;
  let previousStage = 0;

  for (let run = 1; run <= DESCENTS; run += 1) {
    const before = state.stats.playSeconds;
    growToWall(state);
    elapsed += state.stats.playSeconds - before;

    const gained = pendingCrystals(state.highestStage);
    const stats = computeStats(state);

    rows.push({
      run,
      elapsedSeconds: elapsed,
      stage: state.highestStage,
      gain: state.highestStage - previousStage,
      crystals: formatNumber(state.crystals.add(gained)),
      multiplier: formatNumber(stats.crystalMultiplier),
      absorption: formatNumber(stats.absorptionPerSecond),
    });

    previousStage = state.highestStage;
    if (!canCompress(state)) break;
    compress(state, 0);
  }

  return rows;
}

function toMarkdown(rows: StoneRow[]): string {
  const first = rows[0];
  const last = rows[rows.length - 1];
  if (first === undefined || last === undefined) throw new Error('no rows measured');

  const lines = [
    '# Balance report',
    '',
    '> Generated by `npm run balance -- --write`. Do not edit by hand.',
    '',
    'Measured by running the shipping simulation against the simulated player in',
    '`src/game/autoplay.ts`, which buys the cheapest thing it can afford every ten',
    'seconds and compresss once a run stops producing new floors. That shopper is',
    'deliberately naive, so every number here is a **lower bound**: a thoughtful',
    'player does better.',
    '',
    '## What this has to show',
    '',
    'Reachable stage goes as `log(multiplier) / log(healthGrowth)`, and the crystal',
    'multiplier goes as `crystalGrowth^depth`, so one descent maps to the next',
    'roughly linearly. If the gain per descent shrinks toward zero, the runs have a',
    'fixed point: the player compresss forever and never moves, and the game ends',
    'without ever saying so. The gain column is the check.',
    '',
    '| Stone | Wall clock | Stage | Gain | Crystals | Multiplier | Absorption/sec |',
    '| --: | ---------: | ----: | ---: | -----: | ---------: | ---------: |',
  ];

  for (const row of rows) {
    lines.push(
      `| ${row.run} | ${formatDuration(row.elapsedSeconds)} | ${row.stage} | ` +
        `+${row.gain} | ${row.crystals} | ×${row.multiplier} | ${row.absorption} |`,
    );
  }

  const early = rows[Math.min(2, rows.length - 1)];
  lines.push(
    '',
    '## Reading it',
    '',
    `- The first stone walls at stage ${String(first.stage)}, which is past where the`,
    `  compression unlock sits (stage ${String(COMPRESSION_UNLOCK_STAGE)}). A player meets the mechanic the`,
    '  the rest of the game is built around inside their first session, rather',
    '  than grinding against a ceiling with it still greyed out.',
    early === undefined
      ? ''
      : `- Gains climb rather than shrink: +${String(early.gain)} stages by stone ${String(early.run)}, ` +
          `+${String(last.gain)} by stone ${String(last.run)}.`,
    '- No plateau appears across the measured compressions, which is what says the',
    '  relic growth rate sits above the health growth rate rather than below it.',
    '',
  );

  return lines.filter((line) => line !== '').join('\n') + '\n';
}

function toTable(rows: StoneRow[]): string {
  const header = 'stone  wall clock   stage  gain  crystals     multiplier   absorb/sec';
  const body = rows.map((row) =>
    [
      String(row.run).padStart(3),
      formatDuration(row.elapsedSeconds).padStart(11),
      String(row.stage).padStart(6),
      `+${String(row.gain)}`.padStart(5),
      row.crystals.padStart(12),
      `×${row.multiplier}`.padStart(12),
      row.absorption.padStart(12),
    ].join(' '),
  );
  return [header, ...body].join('\n');
}

// English, so a report committed from a Korean machine reads the same as one
// committed from anywhere else.
setLocale('en');

const rows = measure();
console.log(toTable(rows));

if (process.argv.includes('--write')) {
  writeFileSync('docs/BALANCE.md', toMarkdown(rows));
  console.log('\nwrote docs/BALANCE.md');
}
